### ISSUE TITLE
configparser code is wrong for Python 3

### ISSUE THREAD

**Issue by stevegoossens** [isaaczafuta/whatapi#15]
When I attempt to use a config file on Python 3.6, I get this error:
```
(my36project) [root@laptop1 redacted]# python finddirs.py
Cookies loaded
Traceback (most recent call last):
  File "finddirs.py", line 30, in <module>
    apihandle = whatapi.WhatAPI(config_file=config_file, server=server, cookies=cookies)
  File "/root/python-scripts/my36project/lib/python3.6/site-packages/whatapi/whatapi.py", line 31, in __init__
    config = ConfigParser()
TypeError: 'module' object is not callable
```

Reproducing the code in interactive mode clarifies that the code is attempting to call the module as a function:
```
(my36project) [root@laptop1 redacted]# python
Python 3.6.0 (default, Mar 14 2017, 12:24:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser as ConfigParser
>>> config = ConfigParser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

**Comment by stevegoossens** [comment]
This import line works:
```
(my36project) [root@laptop1 redacted]# python
Python 3.6.0 (default, Mar 14 2017, 12:24:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from configparser import ConfigParser as ConfigParser
>>> config = ConfigParser()
>>> config.read('redacted.conf')
['redacted.conf']
```

**Comment by stevegoossens** [comment]
In the meantime, anyone on Python 3 can use code such as the following to implement the config_file loading (there's cookie loading in here too :)):
```python
import pickle
import argparse
from configparser import ConfigParser   # the one in whatapi (0.2.0) is wrong

# vars
config_file = 'redacted.conf'
server = 'https://redacted.ch'

# config file stuff here because it's broken for Python 3 in whatapi
if config_file:
    config = ConfigParser()
    config.read(config_file)
    username = config.get('login', 'username')
    password = config.get('login', 'password')

# cookies
try:
    cookies = pickle.load(open('cookies.dat', 'rb'))
except Exception as e:
    print("Cookies not loaded")
    cookies_loaded = False
else:
    print("Cookies loaded")
    cookies_loaded = True


if cookies_loaded:
    # connect client with cookies
    apihandle = whatapi.WhatAPI(username=username, password=password, server=server, cookies=cookies)
else:
    # connect client without cookies
    apihandle = whatapi.WhatAPI(username=username, password=password, server=server)


# cookies dump
pickle.dump(apihandle.session.cookies, open('cookies.dat', 'wb'))
```

**Comment by stevegoossens** [comment]
has been merged to master
